name: Laravel

on:
  push:
    branches: [ "staging" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2

      - name: Deployment

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |

            cd /var/www/staging.ajaxtradingcorp.com/

            git pull

      - name: Install Dependencies On Server
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Print Environment Variables
        run: |
          echo "DB_HOST: 127.0.0.1"
          echo "DB_PORT: 3306"
          echo "DB_DATABASE: duphilco_ajaxtradingcorp_staging"
          echo "DB_USERNAME: root"
          echo "DB_PASSWORD: RebUseLUbunTuAws2828"

      - name: Migrate Database
        run: php artisan migrate --force
